import { PERMISSIONS } from './permissions'
import type { Permission } from './permissions'
import { ROLES } from './roles'
import type { WorkspaceRole } from './roles'

/**
 * Complete Role-to-Permissions Matrix for MailFlow
 */
export const ROLE_PERMISSIONS: Record<WorkspaceRole, Permission[]> = {
  // 1. OWNER: Full unrestricted access to all system capabilities
  [ROLES.OWNER]: Object.values(PERMISSIONS),

  // 2. ADMIN: Full operations except workspace deletion
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CONTACT_READ,
    PERMISSIONS.CONTACT_CREATE,
    PERMISSIONS.CONTACT_UPDATE,
    PERMISSIONS.CONTACT_DELETE,
    PERMISSIONS.CONTACT_IMPORT,
    PERMISSIONS.CONTACT_EXPORT,
    PERMISSIONS.LIST_READ,
    PERMISSIONS.LIST_CREATE,
    PERMISSIONS.LIST_UPDATE,
    PERMISSIONS.LIST_DELETE,
    PERMISSIONS.SEGMENT_READ,
    PERMISSIONS.SEGMENT_CREATE,
    PERMISSIONS.SEGMENT_UPDATE,
    PERMISSIONS.SEGMENT_DELETE,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.TEMPLATE_CREATE,
    PERMISSIONS.TEMPLATE_UPDATE,
    PERMISSIONS.TEMPLATE_DELETE,
    PERMISSIONS.CAMPAIGN_READ,
    PERMISSIONS.CAMPAIGN_CREATE,
    PERMISSIONS.CAMPAIGN_UPDATE,
    PERMISSIONS.CAMPAIGN_DELETE,
    PERMISSIONS.CAMPAIGN_SEND_TEST,
    PERMISSIONS.CAMPAIGN_SUBMIT,
    PERMISSIONS.CAMPAIGN_APPROVE,
    PERMISSIONS.CAMPAIGN_REJECT,
    PERMISSIONS.CAMPAIGN_SEND,
    PERMISSIONS.CAMPAIGN_PAUSE,
    PERMISSIONS.CAMPAIGN_CANCEL,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEMBER_DELETE,
    PERMISSIONS.SENDER_READ,
    PERMISSIONS.SENDER_MANAGE,
    PERMISSIONS.DOMAIN_READ,
    PERMISSIONS.DOMAIN_MANAGE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_UPDATE,
  ],

  // 3. MARKETING MANAGER: Campaigns, Contacts, Senders, Analytics, Approvals
  [ROLES.MARKETING_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CONTACT_READ,
    PERMISSIONS.CONTACT_CREATE,
    PERMISSIONS.CONTACT_UPDATE,
    PERMISSIONS.CONTACT_DELETE,
    PERMISSIONS.CONTACT_IMPORT,
    PERMISSIONS.CONTACT_EXPORT,
    PERMISSIONS.LIST_READ,
    PERMISSIONS.LIST_CREATE,
    PERMISSIONS.LIST_UPDATE,
    PERMISSIONS.LIST_DELETE,
    PERMISSIONS.SEGMENT_READ,
    PERMISSIONS.SEGMENT_CREATE,
    PERMISSIONS.SEGMENT_UPDATE,
    PERMISSIONS.SEGMENT_DELETE,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.TEMPLATE_CREATE,
    PERMISSIONS.TEMPLATE_UPDATE,
    PERMISSIONS.TEMPLATE_DELETE,
    PERMISSIONS.CAMPAIGN_READ,
    PERMISSIONS.CAMPAIGN_CREATE,
    PERMISSIONS.CAMPAIGN_UPDATE,
    PERMISSIONS.CAMPAIGN_DELETE,
    PERMISSIONS.CAMPAIGN_SEND_TEST,
    PERMISSIONS.CAMPAIGN_SUBMIT,
    PERMISSIONS.CAMPAIGN_APPROVE,
    PERMISSIONS.CAMPAIGN_REJECT,
    PERMISSIONS.CAMPAIGN_SEND,
    PERMISSIONS.CAMPAIGN_PAUSE,
    PERMISSIONS.CAMPAIGN_CANCEL,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.SENDER_READ,
    PERMISSIONS.DOMAIN_READ,
  ],

  // 4. CAMPAIGN EDITOR: Create templates, draft campaigns, send test emails (cannot dispatch to whole list)
  [ROLES.CAMPAIGN_EDITOR]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CONTACT_READ,
    PERMISSIONS.LIST_READ,
    PERMISSIONS.SEGMENT_READ,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.TEMPLATE_CREATE,
    PERMISSIONS.TEMPLATE_UPDATE,
    PERMISSIONS.CAMPAIGN_READ,
    PERMISSIONS.CAMPAIGN_CREATE,
    PERMISSIONS.CAMPAIGN_UPDATE,
    PERMISSIONS.CAMPAIGN_SEND_TEST,
    PERMISSIONS.CAMPAIGN_SUBMIT,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.SENDER_READ,
  ],

  // 5. CONTACT MANAGER: Import/export contacts, manage lists and dynamic segments
  [ROLES.CONTACT_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CONTACT_READ,
    PERMISSIONS.CONTACT_CREATE,
    PERMISSIONS.CONTACT_UPDATE,
    PERMISSIONS.CONTACT_DELETE,
    PERMISSIONS.CONTACT_IMPORT,
    PERMISSIONS.CONTACT_EXPORT,
    PERMISSIONS.LIST_READ,
    PERMISSIONS.LIST_CREATE,
    PERMISSIONS.LIST_UPDATE,
    PERMISSIONS.LIST_DELETE,
    PERMISSIONS.SEGMENT_READ,
    PERMISSIONS.SEGMENT_CREATE,
    PERMISSIONS.SEGMENT_UPDATE,
    PERMISSIONS.SEGMENT_DELETE,
    PERMISSIONS.ANALYTICS_READ,
  ],

  // 6. ANALYST: View reports, export metrics, read campaigns and contacts
  [ROLES.ANALYST]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CONTACT_READ,
    PERMISSIONS.LIST_READ,
    PERMISSIONS.SEGMENT_READ,
    PERMISSIONS.CAMPAIGN_READ,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ANALYTICS_EXPORT,
  ],

  // 7. BILLING MANAGER: View/Manage invoices and quota plans
  [ROLES.BILLING_MANAGER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.WORKSPACE_READ,
  ],

  // 8. VIEWER: Read-only access to basic dashboards and campaigns
  [ROLES.VIEWER]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CAMPAIGN_READ,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.ANALYTICS_READ,
  ],
}

/**
 * Route to Primary Required Permission Mapping
 */
export const ROUTE_REQUIRED_PERMISSIONS: Record<string, Permission> = {
  '/dashboard': PERMISSIONS.DASHBOARD_READ,
  '/contacts': PERMISSIONS.CONTACT_READ,
  '/lists': PERMISSIONS.LIST_READ,
  '/segments': PERMISSIONS.SEGMENT_READ,
  '/campaigns': PERMISSIONS.CAMPAIGN_READ,
  '/templates': PERMISSIONS.TEMPLATE_READ,
  '/reports': PERMISSIONS.ANALYTICS_READ,
  '/analytics': PERMISSIONS.ANALYTICS_READ,
  '/members': PERMISSIONS.MEMBER_READ,
  '/settings/members': PERMISSIONS.MEMBER_READ,
  '/settings/senders': PERMISSIONS.SENDER_READ,
  '/senders': PERMISSIONS.SENDER_READ,
  '/settings/domains': PERMISSIONS.DOMAIN_READ,
  '/domains': PERMISSIONS.DOMAIN_READ,
  '/settings/billing': PERMISSIONS.BILLING_READ,
  '/settings/billing/usage': PERMISSIONS.BILLING_READ,
  '/settings/billing/invoices': PERMISSIONS.BILLING_READ,
  '/billing': PERMISSIONS.BILLING_READ,
  '/settings/workspace': PERMISSIONS.WORKSPACE_READ,
  '/workspace': PERMISSIONS.WORKSPACE_READ,
  '/notifications': PERMISSIONS.DASHBOARD_READ,
  '/settings/profile': PERMISSIONS.DASHBOARD_READ,
  '/profile': PERMISSIONS.DASHBOARD_READ,
}

export function getPermissionsForRole(role: WorkspaceRole): Permission[] {
  return ROLE_PERMISSIONS[role] || []
}
