package com.mailflow.notification.domain.model;

public enum NotificationType {
    CAMPAIGN_COMPLETED,
    CAMPAIGN_FAILED,
    CAMPAIGN_APPROVAL_REQUESTED,
    CAMPAIGN_APPROVED,
    CAMPAIGN_REJECTED,
    CONTACT_IMPORT_COMPLETED,
    CONTACT_IMPORT_FAILED,
    QUOTA_EXCEEDED,
    DOMAIN_VERIFIED,
    DOMAIN_VERIFICATION_FAILED,
    MEMBER_INVITED,
    MEMBER_JOINED,
    MEMBER_ROLE_UPDATED,
    MEMBER_REMOVED,
    SYSTEM_ALERT
}
