spring:
  application:
    name: mailflow

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/mailflow_db}
    username: ${DB_USERNAME:mailflow}
    password: ${DB_PASSWORD:123456a@}
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: MailFlowHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:mailflow.bac.dev@gmail.com}
    password: ${SMTP_PASSWORD:rrng xsar lvfn tyat}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mailflow:
  app:
    client-url: ${APP_CLIENT_URL:http://localhost:5173}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
  mail:
    from-email: ${MAIL_FROM_EMAIL:mailflow.bac.dev@gmail.com}
    from-name: ${MAIL_FROM_NAME:MailFlow Platform}
  campaign:
    send-interval-ms: ${CAMPAIGN_SEND_INTERVAL_MS:5000}
    send-batch-size: ${CAMPAIGN_SEND_BATCH_SIZE:15}
  auth:
    issuer: ${JWT_ISSUER:mailflow-api}
    audience: ${JWT_AUDIENCE:mailflow-api}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:15m}
    refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL:7d}
    remember-me-refresh-token-ttl: ${JWT_REMEMBER_ME_REFRESH_TOKEN_TTL:30d}
    refresh-cookie-name: ${REFRESH_COOKIE_NAME:mf_refresh}
    refresh-cookie-secure: ${REFRESH_COOKIE_SECURE:false}
    refresh-grace-ttl: ${REFRESH_GRACE_TTL:10s}
    refresh-grace-store: ${REFRESH_GRACE_STORE:redis}
    key-id: ${JWT_KEY_ID:mailflow-auth-local}
    private-key: ${JWT_PRIVATE_KEY:}
    public-key: ${JWT_PUBLIC_KEY:}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:dusx4ymdy}
    api-key: ${CLOUDINARY_API_KEY:458343336469922}
    api-secret: ${CLOUDINARY_API_SECRET:dWGPXlmWLzOB88F-6A6Zb3ik5_k}
    folder: ${CLOUDINARY_FOLDER:mailflow/avatars}
    logo-folder: ${CLOUDINARY_LOGO_FOLDER:mailflow/workspace-logos}

server:
  port: 8080
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info